add retrain logic for insufficient data
numaproj/numalogic pull request #321
Opened 2023-11-06 05:32 UTC by s0nicboOm

**DO NOT MERGE**

2023-11-13 22:00 UTC, ab93 requested changes
Minor comment

2023-11-13 22:00 UTC, ab93 commented on numalogic/udfs/tools.py
> +            return None, None, None
convert to named tuple

2023-11-13 23:39 UTC, s0nicboOm commented on numalogic/config/_config.py
> +    data_granularity_sec: int = 60
sure

2023-11-13 23:39 UTC, s0nicboOm commented on numalogic/udfs/tools.py
> +            return None, None, None
sure

2023-11-14 00:31 UTC, ab93 approved these changes
Minor comments. Otherwise LGTM

2023-11-14 00:31 UTC, ab93 commented on numalogic/config/_config.py
> +    data_freq_sec: int = 60
Let's add a docstring for this class

2023-11-14 00:31 UTC, ab93 commented on numalogic/udfs/tools.py
> +    """namedtuple for Dedup Metadata."""
```suggestion
    """Data structure for Dedup Metadata."""
```

2023-11-14 19:02 UTC, merged