feat: ml pipelines
numaproj/numalogic pull request #333
Opened 2023-12-11 11:06 UTC by nkoppisetty

Explain what this PR does.

2023-12-11 21:23 UTC, s0nicboOm requested changes
minor comments

2023-12-11 21:23 UTC, s0nicboOm commented on numalogic/udfs/pipeline.py
> +        The preprocess function here receives data from the data source.
knitpick: can we update the docstring please.

2023-12-11 21:23 UTC, s0nicboOm commented on numalogic/udfs/pipeline.py
> +LOAD_LATEST = os.getenv("LOAD_LATEST", "false").lower() == "true"
Not needed.

2023-12-11 21:23 UTC, s0nicboOm commented on numalogic/udfs/preprocess.py
>          _metric_label_values = (self._vtx, ":".join(keys), data_payload["config_id"])
I think for metrics we need to have pipeline_id also an label. Can you please add a TODO and open an issue and assign it to me.

2023-12-12 09:14 UTC, nkoppisetty commented on numalogic/udfs/pipeline.py
yeah couldn't think of anything, let me know if you have something on mind

2023-12-12 09:25 UTC, nkoppisetty commented on numalogic/udfs/pipeline.py
named it ml_pipeline for now, feel free to update it later with whatever suits best

2023-12-21 20:03 UTC, s0nicboOm commented
Merged the changes after refactoring: https://github.com/numaproj/numalogic/pull/336

2023-12-21 20:03 UTC, closed without merging