add: resume training feature
numaproj/numalogic pull request #38
Opened 2022-10-14 19:09 UTC by s0nicboOm

Signed-off-by: kbatra <kushal_batra@intuit.com>

Explain what this PR does.

2022-10-14 21:42 UTC, vigith approved these changes
LGTM

2022-10-17 15:46 UTC, ab93 requested changes
Minor nitpicks

2022-10-17 17:20 UTC, s0nicboOm commented on numalogic/models/autoencoder/pipeline.py
> +        resume_training: bool = False,
Cool

2022-10-17 18:54 UTC, s0nicboOm commented
duplicate

2022-10-17 18:54 UTC, closed without merging