feat: add transformers model
numaproj/numalogic pull request #8
Opened 2022-07-19 23:32 UTC by s0nicboOm

- Added new Transformers model
- Added docstring for models and pipeline
- Refactored doctring formatting to follow google format
- Rename mlflow.py to mlflow_registry.py
- Added new testcases for mlflow_registry

Signed-off-by: s0nicboOm <i.kushalbatra@gmail.com>

2022-07-20 00:01 UTC, ab93 requested changes
Some comments

2022-07-20 00:01 UTC, ab93 commented on numalogic/tests/models/autoencoder/test_pipeline.py
> +        self.assertEqual(trainer.reconerr_func, np.abs)
Can you also add one test case using the SparseAEPipeline?

2022-07-20 00:08 UTC, s0nicboOm commented on numalogic/models/autoencoder/variants/conv.py
> +    def forward(self, x) -> Tuple[Tensor, Tensor]:
Added it back

2022-07-20 16:49 UTC, ab93 requested changes

2022-07-20 16:49 UTC, ab93 commented on numalogic/models/autoencoder/pipeline.py
> +            Autoencoder Pipeline instance
```suggestion
            AutoencoderPipeline instance
```

2022-07-20 16:49 UTC, ab93 commented on numalogic/models/autoencoder/pipeline.py
> +            Numpy type
```suggestion
            Numpy array
```

2022-07-20 16:49 UTC, ab93 commented on numalogic/models/autoencoder/pipeline.py
> +            numpy type with anomaly scores
```suggestion
            numpy array with anomaly scores
```

2022-07-20 16:49 UTC, ab93 commented on numalogic/models/autoencoder/variants/lstm.py
> +            nn.init.xavier_uniform_(m.weight, gain=2**0.5)
Why did we change here?

2022-07-20 16:49 UTC, ab93 commented on numalogic/models/autoencoder/variants/vanilla.py
> +        r"""Utility function to generate a simple feedforward network layer
```suggestion
        r"""
        Utility function to generate a simple feedforward network layer
```

2022-07-20 16:49 UTC, ab93 commented on numalogic/registry/mlflow_registry.py
> +        Returns: ArtifactDict type object
Explain here what ArtifactDict is in brief, since it is a custom built type

2022-07-20 16:49 UTC, ab93 commented on numalogic/tests/models/autoencoder/test_pipeline.py
> +        trainer.fit(self.X_train)
Add a predict method check and also add asserts

2022-07-21 17:44 UTC, ab93 requested changes
Some comments

2022-07-21 17:44 UTC, ab93 commented on numalogic/models/autoencoder/pipeline.py
> +        Predict function to train autoencoder model
```suggestion
       Return the reconstruction from the model.
```

2022-07-21 17:44 UTC, ab93 commented on numalogic/models/autoencoder/pipeline.py
> +        Score function to train autoencoder model
```suggestion
        Return anomaly score using the calculated threshold
```

2022-07-21 17:44 UTC, ab93 commented on numalogic/models/autoencoder/pipeline.py
> +        recon_err function to calculate reconstruction error
```suggestion
        Returns the reconstruction error
```

2022-07-21 17:44 UTC, ab93 commented on numalogic/models/autoencoder/variants/vanilla.py
> +            nn.init.xavier_uniform_(m.weight, gain=2**0.5)
Why did we change from xavier_normal_ ?

2022-07-21 18:57 UTC, ab93 requested changes

2022-07-21 18:57 UTC, ab93 commented on numalogic/models/autoencoder/variants/vanilla.py
> +            if type(m) == nn.Linear:
Why double if?

2022-07-21 19:44 UTC, ab93 approved these changes
LGTM

2022-07-21 19:45 UTC, merged